# version: "3.8"
# services:
#   mongo:
#     image: mongo:5.0
#     container_name: mongo
#     environment:
#         - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
#         - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
#     restart: unless-stopped
#     ports:
#       - "27017:27017"
#     volumes:
#       - ./mongoDB:/data/db
  # mongo-express:
  #   image: mongo-express
  #   container_name: mexpress
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
  #     - ME_CONFIG_MONGODB_URL=${ME_CONFIG_MONGODB_URL}
  #     - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
  #     - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
  #   links:
  #     - mongo
  #   restart: unless-stopped
  #   ports:
  #     - "8081:8081"

services:
  mongodb-primary:
      image: 'docker.io/bitnami/mongodb:7.0'
      container_name: mongodb-primary
      environment:
        - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
        - MONGODB_REPLICA_SET_MODE=primary
        - MONGODB_REPLICA_SET_KEY=replicasetkey123
        - MONGODB_ROOT_PASSWORD=MongoDB2023

      volumes:
        - 'mongodb_master_data:/bitnami/mongodb'
      ports:
        - 30001:27017

  mongodb-secondary:
      image: 'docker.io/bitnami/mongodb:7.0'
      depends_on:
        - mongodb-primary
      environment:
        - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
        - MONGODB_REPLICA_SET_MODE=secondary
        - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
        - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=MongoDB2023
        - MONGODB_REPLICA_SET_KEY=replicasetkey123
      ports:
        - 30002:27017

  mongodb-arbiter:
      image: 'docker.io/bitnami/mongodb:7.0'
      depends_on:
        - mongodb-primary
      environment:
        - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
        - MONGODB_REPLICA_SET_MODE=arbiter
        - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
        - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=MongoDB2023
        - MONGODB_REPLICA_SET_KEY=replicasetkey123
      ports:
        - 30003:27017

  # mongo-express:
  #   image: mongo-express
  #   container_name: mexpress
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=luizholanda
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=MongoDB2023
  #     - ME_CONFIG_MONGODB_URL=mongodb://luizholanda:MongoDB2023@mongodb-primary:27017/?authSource=admin
  #     - ME_CONFIG_BASICAUTH_USERNAME=admin
  #     - ME_CONFIG_BASICAUTH_PASSWORD=adminExpress
  #   links:
  #     - mongo
  #   restart: unless-stopped
  #   ports:
  #     - "8081:8081"

volumes:
  mongodb_master_data:
    driver: local

# version: "3.8"
# services:
#   mongodb-primary:
#     image: mongo:5.0
#     container_name: mongodb-primary
#     environment:
#       - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
#       - MONGODB_REPLICA_SET_MODE=primary
#       - MONGODB_ROOT_PASSWORD=MongoDB2023
#       - MONGODB_REPLICA_SET_KEY=replicasetkey123
#     volumes:
#       - ./mongoDB:/data/db
#     ports:
#       - '27017:27017'
#     networks:
#       - adonis-net

#   mongodb-secondary:
#     image: mongo:5.0
#     depends_on:
#       - mongodb-primary
#     environment:
#       - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
#       - MONGODB_REPLICA_SET_MODE=secondary
#       - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
#       - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=MongoDB2023
#       - MONGODB_REPLICA_SET_KEY=replicasetkey123
#     networks:
#       - adonis-net

#   mongodb-arbiter:
#     image: mongo:5.0
#     depends_on:
#       - mongodb-primary
#     environment:
#       - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
#       - MONGODB_REPLICA_SET_MODE=arbiter
#       - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
#       - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=MongoDB2023
#       - MONGODB_REPLICA_SET_KEY=replicasetkey123
#     networks:
#       - adonis-net
  
#   mongo-express:
#     image: mongo-express
#     container_name: mexpress
#     environment:
#       - ME_CONFIG_MONGODB_ADMINUSERNAME=luizholanda
#       - ME_CONFIG_MONGODB_ADMINPASSWORD=MongoDB2023
#       - ME_CONFIG_MONGODB_URL=mongodb://root:MongoDB2023@mongodb-primary:27017/admin?authSource=admin
#       - ME_CONFIG_BASICAUTH_USERNAME=admin
#       - ME_CONFIG_BASICAUTH_PASSWORD=adminExpress
#     links:
#       - mongodb-primary
#     restart: unless-stopped
#     ports:
#       - "8081:8081"
#     networks:
#       - adonis-net

# networks:
#   adonis-net:
#     driver: bridge

# volumes:
#   mongodb_master_data:
#     driver: local